# Generated by Django 5.0.7 on 2026-07-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='connector',
            field=models.CharField(choices=[('XT30', 'XT-30'), ('XT60', 'XT-60')], default='XT30', max_length=10),
        ),
    ]
