# Generated by Django 5.0.7 on 2026-07-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0002_battery_connector'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeevent',
            name='charge_current_a',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
