# Generated by Django 5.0.7 on 2026-07-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0003_chargeevent_charge_current_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='weight_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
