# Generated by Django 5.0.7 on 2026-07-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0004_battery_weight_g'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargeevent',
            name='charge_current_a',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
