# Generated by Django 5.0.7 on 2026-07-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0005_alter_chargeevent_charge_current_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargeevent',
            name='charge_current_a',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
