# Generated by Django 5.0.7 on 2026-07-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0006_alter_chargeevent_charge_current_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='connector',
            field=models.CharField(choices=[('XT30', 'XT-30'), ('XT60', 'XT-60'), ('JR/FUTABA', 'JR/Futaba')], default='XT30', max_length=10),
        ),
    ]
