# Generated by Django 5.0.7 on 2026-07-14 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryChemistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('session_start_voltage_per_cell', models.DecimalField(decimal_places=2, help_text='Per-cell voltage at or above which a new battery session is started.', max_digits=4)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive chemistries are hidden from the flight log upload form.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Battery chemistry',
                'verbose_name_plural': 'Battery chemistries',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FlightSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_name', models.CharField(max_length=100)),
                ('cell_count', models.PositiveSmallIntegerField()),
                ('chemistry', models.CharField(max_length=50)),
                ('voltage_threshold', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', 'aircraft_name'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('flight_time', models.DurationField()),
                ('start_voltage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('end_voltage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('filename', models.CharField(max_length=255)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='flightlog.flightsession')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.UniqueConstraint(fields=('filename', 'start_datetime', 'end_datetime'), name='unique_imported_flight'),
        ),
    ]
