# Generated by Django 5.0.7 on 2026-07-14 05:49

from decimal import Decimal

from django.db import migrations


CHEMISTRIES = (
    {
        "name": "LiPo",
        "slug": "lipo",
        "session_start_voltage_per_cell": Decimal("4.10"),
        "sort_order": 10,
    },
    {
        "name": "LiHV",
        "slug": "lihv",
        "session_start_voltage_per_cell": Decimal("4.25"),
        "sort_order": 20,
    },
    {
        "name": "Li-Ion",
        "slug": "li-ion",
        "session_start_voltage_per_cell": Decimal("4.10"),
        "sort_order": 30,
    },
    {
        "name": "LiFEPO",
        "slug": "lifepo",
        "session_start_voltage_per_cell": Decimal("3.65"),
        "sort_order": 40,
    },
)


def create_battery_chemistries(apps, schema_editor):
    BatteryChemistry = apps.get_model(
        "flightlog",
        "BatteryChemistry",
    )

    for chemistry in CHEMISTRIES:
        BatteryChemistry.objects.update_or_create(
            slug=chemistry["slug"],
            defaults={
                "name": chemistry["name"],
                "session_start_voltage_per_cell": (
                    chemistry["session_start_voltage_per_cell"]
                ),
                "sort_order": chemistry["sort_order"],
                "is_active": True,
            },
        )


def remove_battery_chemistries(apps, schema_editor):
    BatteryChemistry = apps.get_model(
        "flightlog",
        "BatteryChemistry",
    )

    BatteryChemistry.objects.filter(
        slug__in=[
            chemistry["slug"]
            for chemistry in CHEMISTRIES
        ],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("flightlog", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_battery_chemistries,
            remove_battery_chemistries,
        ),
    ]