# Generated by Django 5.0.7 on 2026-07-14 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightlog', '0001_initial'),
    ]

    operations = [
    ]
